spring:
  application:
    name: cloud-config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/PuTongGithub/SpringCloudConfig.git
          search-paths: cloud-configs
          username: 282549045@qq.com
          password: uong1620
server:
  port: 12000
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7000/eureka/